In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')

In [14]:
df=pd.read_csv('sonar.csv')
df

V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

        V10  ...     V52     V53     V54     V55     V56     V57     V58  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

        V59     V60  Class  
0    0.0090  0.0032      1  
1    0.0052  0.0044      1  
2    0.0095  0.0078      1  
3    0.0040  0.0117      1  
4    0.0107  0.0094      1  
..      ...     ...    ...  
203  0.0193  0.0157      0  
204  0.0062  0.0067      0  
205  0.0077  0.0031      0  
206  0.0036  0.0048      0  
207  0.0061  0.0115      0  

[208 rows x 61 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      208 non-null    float64
 1   V2      208 non-null    float64
 2   V3      208 non-null    float64
 3   V4      208 non-null    float64
 4   V5      208 non-null    float64
 5   V6      208 non-null    float64
 6   V7      208 non-null    float64
 7   V8      208 non-null    float64
 8   V9      208 non-null    float64
 9   V10     208 non-null    float64
 10  V11     208 non-null    float64
 11  V12     208 non-null    float64
 12  V13     208 non-null    float64
 13  V14     208 non-null    float64
 14  V15     208 non-null    float64
 15  V16     208 non-null    float64
 16  V17     208 non-null    float64
 17  V18     208 non-null    float64
 18  V19     208 non-null    float64
 19  V20     208 non-null    float64
 20  V21     208 non-null    float64
 21  V22     208 non-null    float64
 22  V2

In [16]:
df.describe()

V1          V2          V3          V4          V5          V6  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               V7          V8          V9         V10  ...         V52  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.013420   
std      0.061788    0.085152    0.118387    0.134416  ...    0.009634   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000800   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.007275   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.011400   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.016725   
max      0.372900    0.459000    0.682800    0.710600  ...    0.070900   

              V53         V54         V55         V56         V57         V58  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.010709    0.010941    0.009290    0.008222    0.007820    0.007949   
std      0.007060    0.007301    0.007088    0.005736    0.005785    0.006470   
min      0.000500    0.001000    0.000600    0.000400    0.000300    0.000300   
25%      0.005075    0.005375    0.004150    0.004400    0.003700    0.003600   
50%      0.009550    0.009300    0.007500    0.006850    0.005950    0.005800   
75%      0.014900    0.014500    0.012100    0.010575    0.010425    0.010350   
max      0.039000    0.035200    0.044700    0.039400    0.035500    0.044000   

              V59         V60       Class  
count  208.000000  208.000000  208.000000  
mean     0.007941    0.006507    0.466346  
std      0.006181    0.005031    0.500070  
min      0.000100    0.000600    0.000000  
25%      0.003675    0.003100    0.000000  
50%      0.006400    0.005300    0.000000  
75%      0.010325    0.008525    1.000000  
max      0.036400    0.043900    1.000000  

[8 rows x 61 columns]

In [17]:
df=pd.DataFrame(data=df)
df

V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

        V10  ...     V52     V53     V54     V55     V56     V57     V58  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

        V59     V60  Class  
0    0.0090  0.0032      1  
1    0.0052  0.0044      1  
2    0.0095  0.0078      1  
3    0.0040  0.0117      1  
4    0.0107  0.0094      1  
..      ...     ...    ...  
203  0.0193  0.0157      0  
204  0.0062  0.0067      0  
205  0.0077  0.0031      0  
206  0.0036  0.0048      0  
207  0.0061  0.0115      0  

[208 rows x 61 columns]

In [18]:
x=df.iloc[:,0:-1]
x

V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

        V10  ...     V51     V52     V53     V54     V55     V56     V57  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

        V58     V59     V60  
0    0.0084  0.0090  0.0032  
1    0.0049  0.0052  0.0044  
2    0.0164  0.0095  0.0078  
3    0.0044  0.0040  0.0117  
4    0.0048  0.0107  0.0094  
..      ...     ...     ...  
203  0.0115  0.0193  0.0157  
204  0.0032  0.0062  0.0067  
205  0.0138  0.0077  0.0031  
206  0.0079  0.0036  0.0048  
207  0.0036  0.0061  0.0115  

[208 rows x 60 columns]

In [19]:
y=df.iloc[:,-1]
y

0      1
1      1
2      1
3      1
4      1
      ..
203    0
204    0
205    0
206    0
207    0
Name: Class, Length: 208, dtype: int64

In [20]:
pca=PCA(n_components=10)

In [21]:
x=pca.fit_transform(x)

In [22]:
pd.DataFrame(data=x)

0         1         2         3         4         5         6  \
0    0.576093  0.319393 -0.387291 -0.378009 -0.243780 -0.156243 -0.427736   
1   -0.970667  1.018039  0.834156  0.107423  0.286070  0.178684 -0.260332   
2   -0.325887  0.874209  0.246015  0.863031  0.069110 -0.300833 -0.412807   
3    0.852035  0.690863 -0.013390 -0.110257 -0.554050  0.397968  0.492569   
4   -0.064756  0.222968  0.638601  0.140432  0.135854  0.052881 -0.386558   
..        ...       ...       ...       ...       ...       ...       ...   
203  0.041781 -1.031644  0.265669  0.021516 -0.015439  0.097304  0.003784   
204  0.219149 -1.153807  0.203619  0.045836  0.183272  0.012770  0.078507   
205  0.297733 -1.151860  0.250096 -0.057702  0.163566  0.015275  0.045792   
206 -0.045761 -0.995970  0.199677 -0.066516 -0.147227 -0.084600  0.031038   
207 -0.051115 -0.912526  0.008910 -0.044387 -0.027915 -0.029949  0.033107   

            7         8         9  
0    0.074832 -0.024347  0.318054  
1    0.385600 -0.004030 -0.072529  
2    0.075321 -0.010855 -0.438559  
3   -0.220460  0.537003 -0.436795  
4    0.066549 -0.117006 -0.419277  
..        ...       ...       ...  
203  0.177926 -0.027908 -0.264179  
204  0.264831  0.070749 -0.303296  
205  0.225904  0.072130 -0.313044  
206  0.067444  0.025771 -0.171120  
207 -0.020868 -0.118992 -0.144134  

[208 rows x 10 columns]

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler

In [34]:
scaler=StandardScaler()

In [35]:
x=scaler.fit_transform(x)

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [44]:
lr=LogisticRegression()

In [43]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))


0.8043478260869565


In [45]:
print(confusion_matrix(y_test,predlr))

[[20  1]
 [ 8 17]]


In [46]:
print(classification_report(y_test,predlr))

              precision    recall  f1-score   support

           0       0.71      0.95      0.82        21
           1       0.94      0.68      0.79        25

    accuracy                           0.80        46
   macro avg       0.83      0.82      0.80        46
weighted avg       0.84      0.80      0.80        46



In [47]:
gnb=GaussianNB()

In [48]:
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))

0.8260869565217391


In [49]:
print(confusion_matrix(y_test,predgnb))

[[20  1]
 [ 7 18]]


In [50]:
print(classification_report(y_test,predgnb))

              precision    recall  f1-score   support

           0       0.74      0.95      0.83        21
           1       0.95      0.72      0.82        25

    accuracy                           0.83        46
   macro avg       0.84      0.84      0.83        46
weighted avg       0.85      0.83      0.83        46



In [54]:
svc=SVC()

In [55]:
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))

0.8913043478260869


In [56]:
print(confusion_matrix(y_test,predsvc))

[[21  0]
 [ 5 20]]


In [57]:
print(classification_report(y_test,predsvc))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89        21
           1       1.00      0.80      0.89        25

    accuracy                           0.89        46
   macro avg       0.90      0.90      0.89        46
weighted avg       0.91      0.89      0.89        46



In [58]:
dtc=DecisionTreeClassifier()

In [59]:
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))

0.6521739130434783


In [60]:
print(confusion_matrix(y_test,preddtc))

[[16  5]
 [11 14]]


In [61]:
print(classification_report(y_test,preddtc))

              precision    recall  f1-score   support

           0       0.59      0.76      0.67        21
           1       0.74      0.56      0.64        25

    accuracy                           0.65        46
   macro avg       0.66      0.66      0.65        46
weighted avg       0.67      0.65      0.65        46



In [62]:
rfc=RandomForestClassifier()

In [63]:
rfc.fit(x_train,y_train)
rfc.score(x_train,y_train)
predrfc=rfc.predict(x_test)
print(accuracy_score(y_test,predrfc))

0.8913043478260869


In [64]:
print(confusion_matrix(y_test,predrfc))

[[21  0]
 [ 5 20]]


In [65]:
print(classification_report(y_test,predrfc))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89        21
           1       1.00      0.80      0.89        25

    accuracy                           0.89        46
   macro avg       0.90      0.90      0.89        46
weighted avg       0.91      0.89      0.89        46



In [66]:
import pickle

In [67]:
filename='sonar_dataset.pkl'
pickle.dump(svc,open('sonar_dataset.pkl','wb'))